### ISSUE TITLE
transparencyd cpu high usage

### ISSUE THREAD

**Issue by Matchbox0302** [mrfoxhatails/T480-hackintosh#13]
I'm facing an issue that i've tried to solve by myself but i'm not able to. Deamon transparencyd constantly uses at leas 105% of CPU time when i'm logged into iCloud. If i only log in from Apple Store without activating iCloud transparencyd has normal behaviour. Maybe you have some tips on how i should debug.

**Comment by Fedhirweg** [comment]
I have the same issue! Are you using Sonama as well?
