### ISSUE TITLE
EFI folder not posted

### ISSUE THREAD

**Issue by miwelomali** [mrfoxhatails/T480-hackintosh#15]
Hi I just made the tutorial by valproxy and works awesome ventura OSX, I would like to try to use your EFI on my t480 that is similar to your hardware, great job and thanks for updating the work that they have made to make T480 working on opencore.

**Comment by mrfoxhatails** [comment]
https://github.com/mrfoxhatails/T480-hackintosh/releases/tag/0.9.9

![image](https://github.com/mrfoxhatails/T480-hackintosh/assets/54044230/9510d31c-33c1-4409-8f2e-08a555989946)
